version: "3"

volumes:
  mongodb:

services:
  backend:
    container_name: express
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - API_PORT=${API_PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - $API_PORT:$API_PORT

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - $REACT_APP_PORT:3000
    
  # admin:
  #   container_name: admin
  #   build:
  #     context: admin
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./admin:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - ADMIN_PORT=${ADMIN_PORT}
  #   ports:
  #     - $ADMIN_PORT:3000
  #   stdin_open: true

