version: '3'

services:
  backend:
    container_name: express
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - $API_PORT:$API_PORT
    environment:
      API_PORT: $API_PORT
      MONGO_URI: $MONGO_URI
      NODE_ENV: production


  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - $REACT_APP_PORT:3000