version: "3"

volumes:
  mongodb:

services:
  backend:
    container_name: pmt-backend
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      API_PORT: $API_PORT
      MONGO_URI: $MONGO_URI
      NODE_ENV: production
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - mongodb

  frontend:
    container_name: pmt-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile-prod
      args:
        NODE_ENV: production
    volumes:
      - ./frontend:/usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    depends_on:
      - backend
