version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    
  backend:
    container_name: express
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - API_PORT=${API_PORT}
      - MONGO_URI=${MONGO_URI}
    ports:
      - $API_PORT:$API_PORT

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - $REACT_APP_PORT:3000
